project:
  type: website
  output-dir: _site
  preview:
    port: 5555

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Manual básico de R"
  bread-crumbs: false
  
  repo-url: "https://github.com/mirenbz/r-primers-es"
  repo-actions: [edit, issue]

  navbar:
    pinned: true
    left:
      - about.qmd
      - deustokom-data.qmd
    right:
      - icon: github
        aria-label: github
        href: https://github.com/mirenbz/r-primers
  
  sidebar: 
    style: "docked"
    collapse-level: 2
    contents: 
      - section: "Conceptos básicos"
        contents:
        - auto: "basics/01-visualization-basics"
        - auto: "basics/02-programming-basics"

      - section: "Transformar datos"
        contents:
        - auto: "transform-data/01-tibbles"
        - auto: "transform-data/02-isolating"
        - auto: "transform-data/03-deriving"

      - section: "Visualizar datos"
        contents:
        - auto: "visualize-data/01-eda"
        - auto: "visualize-data/02-bar-charts"
        - auto: "visualize-data/03-histograms"
        - auto: "visualize-data/04-boxplots"
        - auto: "visualize-data/05-scatterplots"
        - auto: "visualize-data/06-line-graphs"
        - auto: "visualize-data/07-overplotting"
        - auto: "visualize-data/08-customize"

      - section: "Ordenar datos"
        contents:
        - auto: "tidy-data/01-reshape-data"

format:
  html:
    theme: 
      # - zephyr
      # - journal
      # - lux
      - sandstone
      # - html/custom.scss
    toc: true
    toc-depth: 3
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
